### ISSUE TITLE
Making the App Look Good on Mobile

### ISSUE THREAD

**Issue by MarcoMorawec** [kcjeon/absolute-first#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by kcjeon** [comment]
Hi, added the "mobile meta tag" to my app. I checked the before and after screenshots, and wow did that make a difference!

**Comment by MarcoMorawec** [comment]
Nice work @kcjeon :)
